<h1>Products</h1>
<table class="table table-bordered table-hover">
    <thead class="thead-light">
        <tr>
            <th>#</th>
            <th>Name</th>
            <th>Description</th>
            <th>Tags</th>
            <th>Price</th>
            <th>Stock</th>
        </tr>
    </thead>
    <tfoot>
        <tr>
            <td colspan="3">Products quantity: <?php echo $data->count(); ?></td>
        </tr>
    </tfoot>
    <tbody>
        <?php foreach ($data as $value) { ?>
            <tr>
                <td><?php echo $value->id; ?></td>
                <td><?php echo $value->name; ?></td>
                <td><?php echo $value->description; ?></td>
                <td><?php echo $value->tags; ?></td>
                <td><?php echo $value->price; ?></td>
                <td><?php echo $value->stock; ?></td>
            </tr>
        <?php } ?>
    </tbody>
</table>