<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="#">Navbar</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav">
      <li class="nav-item active">
        <a class="nav-link" href="/products">Add Product </a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="/products/listProducts">View Products</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="/order/placeorder">Place Order</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="/order/listOrders">View Orders</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="/order/settings">Settings</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="/index/addRoles">Add Role</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="/index/addComponents">Add Component</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="/index/ACL">ACL</a>
      </li>
      
    </ul>
  </div>
</nav>